### ISSUE TITLE
Ubuntu 16.04 problem with "restart nexus"

### ISSUE THREAD

**Issue by farahfa** [jhinrichsen/ansible-nexus#12]
Hello,

I keep on getting the following error:

`fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'nexus'\": "}`

Is that because I'm using Ubuntu 16.04? If so, is this problem coming from the [templates/init-nexus.j2](https://github.com/jhinrichsen/ansible-nexus/blob/master/templates/init-nexus.j2)?

**Comment by farahfa** [comment]
I changed those lines to:

```
- name: Copy the /etc/init.d/nexus file
  template: src=init-nexus.j2 dest=/etc/init.d/nexus owner=root group=root mode=0755 backup=yes
  when: ansible_os_family == "Debian"
  notify:
    - 'restart nexus'

- name: Register service with chkconfig system
  service: name=nexus enabled=yes
  when: ansible_os_family == "Debian"

- name: Set service start/stop order
  sudo: yes
  command: service nexus restart
  when: ansible_os_family == "Debian"
```

And I've copied the ${NEXUS_HOME}/bin/nexus and pasted it in templates to replace `init-nexus.j2` while changing the `NEXUS_HOME` inside that file to match the old `init-nexus.j2`.

But I still get:

`fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'nexus'\": "}`

**Comment by farahfa** [comment]
Nevermind, I've fixed the problem:

I've added the following to the `tasks/main.yml`:

```
- name: Copy the /etc/systemd/system/nexus.service file
  template: src=systemd-nexus.j2
            dest=/etc/systemd/system/nexus.service
            owner=root
            group=root
            mode=0664
            backup=yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"
  notify:
    - 'restart nexus'
  tags:
    - ansible-nexus

- name: Register service with systemd
  become: true
  command: "{{ item }}"
  with_items:
    - systemctl daemon-reload
    - systemctl enable nexus.service
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"
  tags:
    - ansible-nexus

- name: Set systemctl service start/stop order
  become: true
  command: systemctl restart nexus.service
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"
  tags:
    - ansible-nexus
```

And created the following in `templates/systemd-nexus.j2`:

```
[Unit]
Description=Nexus Repository Manager Professional
After=network.target

[Service]
Type=forking
ExecStart={{ nexus_installation_dir }}/nexus-latest/bin/nexus start
ExecReload={{ nexus_installation_dir }}/nexus-latest/bin/nexus restart
ExecStop={{ nexus_installation_dir }}/nexus-latest/bin/nexus stop
User=nexus
Restart=on-abort

[Install]
WantedBy=multi-user.target
```
